"""Exchange adapter ABC and typed event/data contracts.

Every exchange adapter implements :class:`ExchangeAdapter`.  Strategies never
see a wire format — the adapter translates to/from these typed structures.

Learnings driving this surface:
- polymarket-auth-and-signing.md: two auth tiers, EIP-712 order struct fields
- polymarket-idempotency-and-cancels.md: four cancel methods; no native client-id
- polymarket-settlement.md: settlement fields from Gamma + CLOB
- polymarket-errors-and-rate-limits.md: error categories (retryable/fatal/risk)
"""

from __future__ import annotations

__all__ = [
    "CancelEvent",
    "ExchangeAdapter",
    "ExchangeEvent",
    "FillEvent",
    "Market",
    "MarketClosedToTradingEvent",
    "MarketFinalizedEvent",
    "MarketOpenedEvent",
    "MarketResolvedEvent",
    "Mode",
    "OrderIntent",
    "OrderResult",
    "OrderTemplate",
    "RejectionEvent",
    "SettlementEvent",
    "Side",
]

import logging
from abc import ABC, abstractmethod
from collections.abc import AsyncIterator, Mapping
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import StrEnum
from typing import Any, ClassVar, Literal

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class Mode(StrEnum):
    """Execution mode for an adapter.  Paper routes through the in-memory
    simulator; live transmits real orders.  Default for every new strategy
    is paper until promoted (invariant 1 / three-lock rule)."""

    PAPER = "paper"
    LIVE = "live"


class Side(StrEnum):
    """Order side.  Maps to Polymarket side=0 (BUY) / side=1 (SELL) in Phase 4."""

    BUY = "buy"
    SELL = "sell"


# ---------------------------------------------------------------------------
# Market
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Market:
    """Canonical description of a tradeable market.

    Args:
        market_id: Canonical identifier.  For Polymarket this is the
            ``condition_id`` (hex string).
        token_id: For Polymarket the ERC-1155 outcome token id for the
            specific YES/NO side being traded.  Other venues may use a
            different concept.
        tick_size: Minimum price increment (Decimal, never float).
        min_size: Minimum order size (Decimal, never float).
        venue: Lowercase venue name, e.g. ``"polymarket"`` or ``"kalshi"``.
    """

    market_id: str
    token_id: str
    tick_size: Decimal
    min_size: Decimal
    venue: str


# ---------------------------------------------------------------------------
# Order intent and template
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class OrderTemplate:
    """Strategy-facing order description that intentionally omits
    ``client_order_id``.

    Strategies always pass an :class:`OrderTemplate` to
    :meth:`~src.bots.base.BaseBot.place`; the base bot wraps it into a full
    :class:`OrderIntent` with a deterministic id so strategies can never
    fabricate ids (invariant 2).
    """

    market: Market
    side: Side
    price: Decimal
    size: Decimal


@dataclass(frozen=True, slots=True)
class OrderIntent:
    """Fully-formed order, including the deterministic ``client_order_id``
    generated by :class:`~src.bots.base.BaseBot`.

    The adapter translates these fields into the exchange wire format.
    It must NOT add business logic — only mapping.

    Note: these are *not* exchange-native fields. Polymarket's EIP-712 struct
    (salt, makerAmount, takerAmount, …) is derived by the adapter in Phase 4.
    The ``client_order_id`` maps to ``salt`` deterministically there.

    Args:
        client_order_id: Hex string produced by BaseBot via blake2s.  Stable
            across retries of the same logical intent.
        market: The market this order targets.
        side: Buy or sell.
        price: Limit price expressed in the market's collateral unit (Decimal).
        size: Order size in shares/contracts (Decimal).
    """

    client_order_id: str
    market: Market
    side: Side
    price: Decimal
    size: Decimal


# ---------------------------------------------------------------------------
# Order result
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class OrderResult:
    """Adapter's response to a :class:`OrderIntent` placement attempt.

    Args:
        client_order_id: Echoed from the intent.
        exchange_order_id: Exchange-assigned id, or ``None`` on rejection.
        accepted: ``True`` when the exchange acknowledged the order.
        reason: Human-readable error description if ``accepted`` is ``False``.
        raw: Full upstream response payload, stored verbatim in audit_log.
    """

    client_order_id: str
    exchange_order_id: str | None  # None on rejection
    accepted: bool
    reason: str | None  # error message if not accepted
    raw: Mapping[str, Any]  # stored verbatim in audit_log


# ---------------------------------------------------------------------------
# Typed events
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class FillEvent:
    """An order received a (partial or full) fill.

    Driven by polymarket-api-shape.md: fills arrive via WS ``last_trade_price``
    and the authenticated ``/trades`` endpoint (Phase 4).
    """

    client_order_id: str
    exchange_order_id: str
    fill_price: Decimal
    fill_size: Decimal
    fee: Decimal  # in collateral units
    fill_at: datetime


@dataclass(frozen=True, slots=True)
class CancelEvent:
    """An order was cancelled — either by the bot or by the exchange.

    ``requested=True`` means our adapter called cancel explicitly;
    ``requested=False`` means the exchange cancelled it (e.g. market close,
    expired order).  Driven by polymarket-idempotency-and-cancels.md.
    """

    client_order_id: str
    exchange_order_id: str
    cancelled_at: datetime
    requested: bool  # True = we cancelled; False = exchange-initiated


@dataclass(frozen=True, slots=True)
class RejectionEvent:
    """An order was rejected immediately.

    ``category`` drives the retry policy:
    - ``"retryable"`` — transient (rate limit, temporary overload).
    - ``"fatal"`` — will never succeed with the same intent (bad price, size).
    - ``"risk"`` — tripped a BaseBot risk cap before reaching the exchange.

    Categorisation is from polymarket-errors-and-rate-limits.md.
    """

    client_order_id: str
    reason: str
    category: Literal["retryable", "fatal", "risk"]
    rejected_at: datetime


@dataclass(frozen=True, slots=True)
class SettlementEvent:
    """A market resolved and payouts are known.

    Driven by polymarket-settlement.md: payout comes from Gamma
    ``outcomePrices``, indexed by ``clobTokenIds``.

    Args:
        market_id: ``condition_id`` for Polymarket.
        token_id: ERC-1155 token the strategy held.
        payout: 0 or 1 for binary markets; fractional for scalar/categorical
            (not yet observed empirically — see settlement learning).
        settled_at: UTC datetime from Gamma ``umaEndDate`` / ``closedTime``.
        resolver: ``umaResolutionStatus`` value or arbitrator contract address.
        raw: Upstream Gamma row, stored in audit_log.
    """

    market_id: str
    token_id: str
    payout: Decimal  # 0 or 1 for binary; fractional for scalar/categorical
    settled_at: datetime
    resolver: str
    raw: Mapping[str, Any]


@dataclass(frozen=True, slots=True)
class MarketOpenedEvent:
    """A market has opened for trading.

    Args:
        market_id: Canonical market identifier (condition_id for Polymarket).
        token_id: ERC-1155 outcome token ID.
        opened_at: UTC datetime when the market opened.
    """

    market_id: str
    token_id: str
    opened_at: datetime


@dataclass(frozen=True, slots=True)
class MarketClosedToTradingEvent:
    """A market has stopped accepting new orders.

    Note: On Polymarket, ``active`` does NOT flip on close.  Use
    ``closed == false`` and ``accepting_orders == true`` to determine
    tradability, not ``active``.

    Args:
        market_id: Canonical market identifier.
        token_id: ERC-1155 outcome token ID.
        closed_at: UTC datetime when trading closed.
    """

    market_id: str
    token_id: str
    closed_at: datetime


@dataclass(frozen=True, slots=True)
class MarketResolvedEvent:
    """A market has been resolved with a known payout.

    Args:
        market_id: Canonical market identifier.
        token_id: ERC-1155 outcome token ID.
        payout: Payout per share (0 or 1 for binary; fractional for scalar).
        resolved_at: UTC datetime when resolution was published.
    """

    market_id: str
    token_id: str
    payout: Decimal
    resolved_at: datetime


@dataclass(frozen=True, slots=True)
class MarketFinalizedEvent:
    """A market has been finalized — payouts are claimable on-chain.

    Args:
        market_id: Canonical market identifier.
        token_id: ERC-1155 outcome token ID.
        finalized_at: UTC datetime when finalization occurred.
    """

    market_id: str
    token_id: str
    finalized_at: datetime


#: Union type for all events the adapter may emit.
ExchangeEvent = (
    FillEvent
    | CancelEvent
    | RejectionEvent
    | SettlementEvent
    | MarketOpenedEvent
    | MarketClosedToTradingEvent
    | MarketResolvedEvent
    | MarketFinalizedEvent
)


# ---------------------------------------------------------------------------
# Abstract adapter
# ---------------------------------------------------------------------------


class ExchangeAdapter(ABC):
    """Abstract base for all exchange integrations.

    Subclasses implement the venue-specific wire translation.  The strategy
    and BaseBot code exclusively operate on the typed structures above.

    Class attribute:
        venue: Lowercase venue name string (e.g. ``"polymarket"``).  Must be
            overridden in every concrete adapter.

    Args:
        mode: :class:`Mode.PAPER` routes through the in-process simulator;
            :class:`Mode.LIVE` transmits real orders.
    """

    venue: ClassVar[str]

    def __init__(self, mode: Mode) -> None:
        self._mode = mode

    async def __aenter__(self) -> "ExchangeAdapter":
        """Enter the adapter context — subclasses override to open connections."""
        return self

    async def __aexit__(self, *_: object) -> None:
        """Exit the adapter context — subclasses override to close connections."""

    @property
    def mode(self) -> Mode:
        """Current execution mode of this adapter."""
        return self._mode

    @abstractmethod
    async def place(self, intent: OrderIntent) -> OrderResult:
        """Submit an order to the exchange (or simulator in paper mode).

        The adapter is responsible for idempotent retries: the same
        ``client_order_id`` arriving twice must not produce two live orders.
        See polymarket-idempotency-and-cancels.md for the Option A / B
        mapping decision (deferred to Phase 4).

        Args:
            intent: Fully-formed order intent including the deterministic id.

        Returns:
            :class:`OrderResult` with the exchange's response.
        """

    @abstractmethod
    async def cancel(self, client_order_id: str) -> bool:
        """Cancel a single order by our deterministic id.

        Idempotent: a second cancel of an already-cancelled order MUST return
        ``False``, not raise.  This mirrors the Polymarket cancel-idempotency
        empirical open question — the adapter must handle both 200-noop and
        4xx-already-cancelled from the upstream.

        Args:
            client_order_id: The id used when placing the order.

        Returns:
            ``True`` if the order was found and cancelled; ``False`` if it was
            already gone (filled, cancelled, expired).
        """

    @abstractmethod
    async def cancel_all(self, market_id: str | None = None) -> int:
        """Cancel every open order, optionally scoped to one market.

        Used by the kill-switch path (Phase 6) and by the bot's run loop when
        the kill switch is tripped.  Polymarket exposes
        ``cancel_market_orders(market=condition_id)`` for the scoped variant —
        much cheaper than per-order cancels under kill-switch pressure.

        Args:
            market_id: If supplied, cancel only orders in this market.
                If ``None``, cancel all open orders for the wallet/account.

        Returns:
            Number of orders cancelled.
        """

    @abstractmethod
    async def get_market(self, market_id: str) -> Market:
        """Fetch current market metadata (tick size, min size, status).

        Called by the bot at startup and periodically to refresh parameters.
        The adapter caches as appropriate; the strategy always receives fresh
        data via :class:`~src.signals.base.SignalSnapshot`.

        Args:
            market_id: Canonical market identifier.

        Returns:
            :class:`Market` populated from the exchange.
        """

    @abstractmethod
    def events(self) -> AsyncIterator[ExchangeEvent]:
        """Async generator producing typed exchange events.

        The bot's ``run`` loop (Phase 5+) consumes this in a background task.
        Events include fills, cancels, rejections, and settlements.  The
        generator should run indefinitely until the adapter is closed.

        Yields:
            :class:`ExchangeEvent` instances in arrival order.
        """
