"""SQLAlchemy ORM models for durable bot state.

# Phase 3 will expand these schemas — column lists are intentionally minimal stubs.
"""

from __future__ import annotations

from sqlalchemy import Boolean, Column, DateTime, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.sql import func


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""


class BotState(Base):
    """Periodic JSONB snapshots written by each bot after every successful tick.

    The manager reads the latest row when rehydrating a crashed bot.
    """

    __tablename__ = "bot_state"

    id = Column(Integer, primary_key=True, autoincrement=True)
    bot_id = Column(String(255), nullable=False, index=True)
    snapshot_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    version = Column(Integer, nullable=False, default=1)
    # Full strategy state serialised as JSONB. Phase 3 will document the schema contract.
    state = Column(JSONB, nullable=False)


class AuditLog(Base):
    """Append-only record of every order intent and result.

    INVARIANT: no DELETE or UPDATE ever touches this table.
    Corrections are new rows referencing the original via original_id.
    """

    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    bot_id = Column(String(255), nullable=False, index=True)
    # client_order_id generated by BaseBot — deterministic, never reused.
    client_order_id = Column(UUID(as_uuid=False), nullable=False, unique=True)
    event_type = Column(String(64), nullable=False)  # e.g. "order_intent", "order_result"
    payload = Column(JSONB, nullable=False)
    # Non-null only for correction rows.
    original_id = Column(Integer, nullable=True)


class KillSwitch(Base):
    """Global kill-switch state.  Exactly one row expected (id=1).

    BaseBot.place() checks this before every order.  Tripping it cancels all
    open orders and freezes new placement across all bots.
    """

    __tablename__ = "kill_switch"

    id = Column(Integer, primary_key=True)
    active = Column(Boolean, nullable=False, default=False)
    tripped_at = Column(DateTime(timezone=True), nullable=True)
    tripped_by = Column(Text, nullable=True)  # free-text reason / operator id
